// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace schema
{

public enum Command : sbyte
{
 JoinRoom = 1,
 QuitRoom = 2,
};


}
