// automatically generated by the FlatBuffers compiler, do not modify

package schema;

public final class Command {
  private Command() { }
  public static final byte JoinRoom = 1;
  public static final byte QuitRoom = 2;

  public static final String[] names = { "JoinRoom", "QuitRoom", };

  public static String name(int e) { return names[e - JoinRoom]; }
}

