// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CredentialToken extends Table {
  public static CredentialToken getRootAsCredentialToken(ByteBuffer _bb) { return getRootAsCredentialToken(_bb, new CredentialToken()); }
  public static CredentialToken getRootAsCredentialToken(ByteBuffer _bb, CredentialToken obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public CredentialToken __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String token() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createCredentialToken(FlatBufferBuilder builder,
      int tokenOffset) {
    builder.startObject(1);
    CredentialToken.addToken(builder, tokenOffset);
    return CredentialToken.endCredentialToken(builder);
  }

  public static void startCredentialToken(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(0, tokenOffset, 0); }
  public static int endCredentialToken(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // token
    return o;
  }
}

