// automatically generated by the FlatBuffers compiler, do not modify

package Schema;

public final class Data {
  private Data() { }
  public static final byte NONE = 0;
  public static final byte CredentialToken = 1;

  public static final String[] names = { "NONE", "CredentialToken", };

  public static String name(int e) { return names[e]; }
}

