// automatically generated by the FlatBuffers compiler, do not modify

package schema;

public final class Data {
  private Data() { }
  public static final byte NONE = 0;
  public static final byte JoinRoomCommand = 1;
  public static final byte RoomInfo = 2;
  public static final byte PlayerUpdate = 3;
  public static final byte ErrorMessage = 4;

  public static final String[] names = { "NONE", "JoinRoomCommand", "RoomInfo", "PlayerUpdate", "ErrorMessage", };

  public static String name(int e) { return names[e]; }
}

