// automatically generated by the FlatBuffers compiler, do not modify

package schema;

public final class ErrorCode {
  private ErrorCode() { }
  public static final byte Unknown = 0;
  public static final byte INVALID_AUTH = 1;
  public static final byte ROOM_NOT_FOUND = 2;

  public static final String[] names = { "Unknown", "INVALID_AUTH", "ROOM_NOT_FOUND", };

  public static String name(int e) { return names[e]; }
}

