// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ErrorMessage extends Table {
  public static ErrorMessage getRootAsErrorMessage(ByteBuffer _bb) { return getRootAsErrorMessage(_bb, new ErrorMessage()); }
  public static ErrorMessage getRootAsErrorMessage(ByteBuffer _bb, ErrorMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ErrorMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte code() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String error() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createErrorMessage(FlatBufferBuilder builder,
      byte code,
      int errorOffset) {
    builder.startObject(2);
    ErrorMessage.addError(builder, errorOffset);
    ErrorMessage.addCode(builder, code);
    return ErrorMessage.endErrorMessage(builder);
  }

  public static void startErrorMessage(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addCode(FlatBufferBuilder builder, byte code) { builder.addByte(0, code, 0); }
  public static void addError(FlatBufferBuilder builder, int errorOffset) { builder.addOffset(1, errorOffset, 0); }
  public static int endErrorMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 6);  // error
    return o;
  }
}

