// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ErrorMessage extends Table {
  public static ErrorMessage getRootAsErrorMessage(ByteBuffer _bb) { return getRootAsErrorMessage(_bb, new ErrorMessage()); }
  public static ErrorMessage getRootAsErrorMessage(ByteBuffer _bb, ErrorMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ErrorMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String error() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer errorAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createErrorMessage(FlatBufferBuilder builder,
      int errorOffset) {
    builder.startObject(1);
    ErrorMessage.addError(builder, errorOffset);
    return ErrorMessage.endErrorMessage(builder);
  }

  public static void startErrorMessage(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addError(FlatBufferBuilder builder, int errorOffset) { builder.addOffset(0, errorOffset, 0); }
  public static int endErrorMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // error
    return o;
  }
}

