// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class GameCommand extends Table {
  public static GameCommand getRootAsGameCommand(ByteBuffer _bb) { return getRootAsGameCommand(_bb, new GameCommand()); }
  public static GameCommand getRootAsGameCommand(ByteBuffer _bb, GameCommand obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public GameCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte type() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createGameCommand(FlatBufferBuilder builder,
      byte type) {
    builder.startObject(1);
    GameCommand.addType(builder, type);
    return GameCommand.endGameCommand(builder);
  }

  public static void startGameCommand(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addType(FlatBufferBuilder builder, byte type) { builder.addByte(0, type, 0); }
  public static int endGameCommand(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

