// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class JoinRoomCommand extends Table {
  public static JoinRoomCommand getRootAsJoinRoomCommand(ByteBuffer _bb) { return getRootAsJoinRoomCommand(_bb, new JoinRoomCommand()); }
  public static JoinRoomCommand getRootAsJoinRoomCommand(ByteBuffer _bb, JoinRoomCommand obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public JoinRoomCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String token() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String roomId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer roomIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createJoinRoomCommand(FlatBufferBuilder builder,
      int tokenOffset,
      int roomIdOffset) {
    builder.startObject(2);
    JoinRoomCommand.addRoomId(builder, roomIdOffset);
    JoinRoomCommand.addToken(builder, tokenOffset);
    return JoinRoomCommand.endJoinRoomCommand(builder);
  }

  public static void startJoinRoomCommand(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(0, tokenOffset, 0); }
  public static void addRoomId(FlatBufferBuilder builder, int roomIdOffset) { builder.addOffset(1, roomIdOffset, 0); }
  public static int endJoinRoomCommand(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // token
    return o;
  }
}

