// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerInfo extends Table {
  public static PlayerInfo getRootAsPlayerInfo(ByteBuffer _bb) { return getRootAsPlayerInfo(_bb, new PlayerInfo()); }
  public static PlayerInfo getRootAsPlayerInfo(ByteBuffer _bb, PlayerInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PlayerInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createPlayerInfo(FlatBufferBuilder builder,
      int nameOffset) {
    builder.startObject(1);
    PlayerInfo.addName(builder, nameOffset);
    return PlayerInfo.endPlayerInfo(builder);
  }

  public static void startPlayerInfo(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static int endPlayerInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

