// automatically generated by the FlatBuffers compiler, do not modify

package schema;

public final class PlayerStatus {
  private PlayerStatus() { }
  public static final byte Unknown = 0;
  public static final byte Arrive = 1;
  public static final byte Left = 2;

  public static final String[] names = { "Unknown", "Arrive", "Left", };

  public static String name(int e) { return names[e]; }
}

