// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerUpdate extends Table {
  public static PlayerUpdate getRootAsPlayerUpdate(ByteBuffer _bb) { return getRootAsPlayerUpdate(_bb, new PlayerUpdate()); }
  public static PlayerUpdate getRootAsPlayerUpdate(ByteBuffer _bb, PlayerUpdate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PlayerUpdate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte status() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public PlayerInfo player() { return player(new PlayerInfo()); }
  public PlayerInfo player(PlayerInfo obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createPlayerUpdate(FlatBufferBuilder builder,
      byte status,
      int playerOffset) {
    builder.startObject(2);
    PlayerUpdate.addPlayer(builder, playerOffset);
    PlayerUpdate.addStatus(builder, status);
    return PlayerUpdate.endPlayerUpdate(builder);
  }

  public static void startPlayerUpdate(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(0, status, 0); }
  public static void addPlayer(FlatBufferBuilder builder, int playerOffset) { builder.addOffset(1, playerOffset, 0); }
  public static int endPlayerUpdate(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

