// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ReconnectKey extends Table {
  public static ReconnectKey getRootAsReconnectKey(ByteBuffer _bb) { return getRootAsReconnectKey(_bb, new ReconnectKey()); }
  public static ReconnectKey getRootAsReconnectKey(ByteBuffer _bb, ReconnectKey obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public ReconnectKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String key() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer keyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createReconnectKey(FlatBufferBuilder builder,
      int keyOffset) {
    builder.startObject(1);
    ReconnectKey.addKey(builder, keyOffset);
    return ReconnectKey.endReconnectKey(builder);
  }

  public static void startReconnectKey(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addKey(FlatBufferBuilder builder, int keyOffset) { builder.addOffset(0, keyOffset, 0); }
  public static int endReconnectKey(FlatBufferBuilder builder) {
    int o = builder.endObject();
    builder.required(o, 4);  // key
    return o;
  }
}

