// automatically generated by the FlatBuffers compiler, do not modify

package schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RoomInfo extends Table {
  public static RoomInfo getRootAsRoomInfo(ByteBuffer _bb) { return getRootAsRoomInfo(_bb, new RoomInfo()); }
  public static RoomInfo getRootAsRoomInfo(ByteBuffer _bb, RoomInfo obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public RoomInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PlayerInfo players(int j) { return players(new PlayerInfo(), j); }
  public PlayerInfo players(PlayerInfo obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int playersLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }

  public static int createRoomInfo(FlatBufferBuilder builder,
      int playersOffset) {
    builder.startObject(1);
    RoomInfo.addPlayers(builder, playersOffset);
    return RoomInfo.endRoomInfo(builder);
  }

  public static void startRoomInfo(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addPlayers(FlatBufferBuilder builder, int playersOffset) { builder.addOffset(0, playersOffset, 0); }
  public static int createPlayersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startPlayersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRoomInfo(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

